/***************************************************************************
 *   Copyright (C) 2005 by Ambertation                                     *
 *   quaxi@ambertation.de                                                  *
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 *   This program is distributed in the hope that it will be useful,       *
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of        *
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the         *
 *   GNU General Public License for more details.                          *
 *                                                                         *
 *   You should have received a copy of the GNU General Public License     *
 *   along with this program; if not, write to the                         *
 *   Free Software Foundation, Inc.,                                       *
 *   59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.             *
 ***************************************************************************/
using System;
using System.Windows.Forms;
using System.Collections;

namespace SimPe
{
	/// <summary>
	/// This will be assigned to all ListViewItems that are generated by the <see cref="TreeNodeTag.RefreshResourceList"/>
	/// delegate.
	/// </summary>
	public class ListViewTag : System.IDisposable
	{
		SimPe.Interfaces.Scenegraph.IScenegraphFileIndexItem fii;
		/// <summary>
		/// Returns the stored FileIndexItem describing the Resource
		/// </summary>
		public SimPe.Interfaces.Scenegraph.IScenegraphFileIndexItem Resource
		{
			get { return fii; }
		}

		/// <summary>
		/// Create a new Instance
		/// </summary>
		/// <param name="pfd"></param>
		internal ListViewTag(SimPe.Interfaces.Files.IPackedFileDescriptor pfd, SimPe.Interfaces.Files.IPackageFile pkg) 
		{
			fii = new SimPe.Plugin.FileIndexItem(pfd, pkg);
		}
		#region IDisposable Member

		public void Dispose()
		{
			fii = null;
		}

		#endregion
	}
}
